### ISSUE TITLE
i have this errors

### ISSUE THREAD

**Issue by CitizenOnTop** [Xiloe/OdinV3#2]
![Screenshot_6](https://user-images.githubusercontent.com/128318975/227750536-c157ea7d-fa2d-4d88-b4f4-08a195a9e400.png)
![Screenshot_7](https://user-images.githubusercontent.com/128318975/227750540-5cb54566-6c78-4f41-8b8a-5524f523e5df.png)
can u help me

**Comment by Xiloe** [comment]
skill issue

**Comment by CitizenOnTop** [comment]
why you dont help me you dumb?

**Comment by CitizenOnTop** [comment]
if you don't help us off then

**Comment by Xiloe** [comment]
I don't give a fuck, skill issue
